server:
  port: 8080

spring:
  datasource:
<<<<<<< HEAD
    url: ${DB_URL:jdbc:mysql://localhost:3306/dochi}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:ssafy}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:2000ms}
=======
    url: jdbc:mysql://localhost:3306/dochi
    username: root
    password: ssafy
>>>>>>> da60d044a823cd55845fe066e9fc642f5e24a7f4

management:
  endpoints:
    web:
      exposure:
        include: health,info